export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CHECK_AUTH = 'CHECK_AUTH';
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';
export const CHECK_AUTH_FAIL = 'CHECK_AUTH_FAIL';

export const REGISTER_DRIVER = 'REGISTER_DRIVER';
export const REGISTER_DRIVER_SUCCESS = 'REGISTER_DRIVER_SUCCESS';
export const REGISTER_DRIVER_FAIL = 'REGISTER_DRIVER_FAIL';
export const REGISTER_DRIVER_DONE = 'REGISTER_DRIVER_DONE';

export const REGISTER_CAR = 'REGISTER_CAR';
export const REGISTER_CAR_SUCCESS = 'REGISTER_CAR_SUCCESS';
export const REGISTER_CAR_FAIL = 'REGISTER_CAR_FAIL';
export const REGISTER_CAR_DONE = 'REGISTER_CAR_DONE';
